/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ConnectionImport } from './routes/$connection'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ConnectionRoute = ConnectionImport.update({
  id: '/$connection',
  path: '/$connection',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$connection': {
      id: '/$connection'
      path: '/$connection'
      fullPath: '/$connection'
      preLoaderRoute: typeof ConnectionImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$connection': typeof ConnectionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$connection': typeof ConnectionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$connection': typeof ConnectionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$connection'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$connection'
  id: '__root__' | '/' | '/$connection'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionRoute: typeof ConnectionRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionRoute: ConnectionRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$connection"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$connection": {
      "filePath": "$connection.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
