# this is a phenominally good idea to have on
doAuth: true

# The port to serve on
port: 3120

# the directory to store vaults in
# all directory vaults are *relative* to this dir
#
# if you want your vaults to be able to be anywhere,
# just set vaultsDirectory to / and use absolute paths
vaultsDirectory: "store/vaults"


# relative to the directory the server is started in
#
# each line that doesn't begin with a # is considered a valid key to
# connect to the server with
keyfilePath: "keyfile.txt"


# This is the important property. Put all of
# the vaults you need here. See the schema below
#
# name: <string>                          # the name of the vault
# encrypted: <boolean>                    # Whether its assumed that the vault is encrypted or not
# type: "directory" | "bucket"
#
# if directory type:
# directory: <string>
#
#
vaults:
  - name: "my-vault"
    type: "directory"
    encrypted: false
    directory: "vault-one"
